### ISSUE TITLE
Bootstrap - courses & tutorials

### ISSUE THREAD

**Issue by bassmedia** [damianosiak/S2RouteAssistant#11]
Bootstrap - courses & tutorials

1. Include Bootstrap via CDN
`<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">`
`<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>`

2. Bootstrap compiled CSS and JS download
https://getbootstrap.com/docs/5.3/getting-started/download/

3. Bootstrap 5 Tutorial
https://getbootstrap.com/docs/5.3/
https://www.w3schools.com/bootstrap5/
https://www.tutorialspoint.com/bootstrap/

4. Buttons
https://getbootstrap.com/docs/5.3/components/buttons/
https://www.w3schools.com/bootstrap5/bootstrap_buttons.php
https://www.tutorialspoint.com/bootstrap/bootstrap_buttons.htm

5. Tables
https://getbootstrap.com/docs/5.3/content/tables/
https://www.w3schools.com/bootstrap5/bootstrap_tables.php
https://www.tutorialspoint.com/bootstrap/bootstrap_tables.htm

6. Alerts
https://getbootstrap.com/docs/5.3/components/alerts/
https://www.w3schools.com/bootstrap5/bootstrap_alerts.php
https://www.tutorialspoint.com/bootstrap/bootstrap_alerts.htm

7. Progress
https://getbootstrap.com/docs/5.3/components/progress/
https://www.w3schools.com/bootstrap5/bootstrap_progressbars.php
https://www.tutorialspoint.com/bootstrap/bootstrap_progress.htm

8. Form control
https://getbootstrap.com/docs/5.3/forms/form-control/
https://www.w3schools.com/bootstrap5/bootstrap_forms.php
https://www.tutorialspoint.com/bootstrap/bootstrap_form_control.htm

9. Popovers
https://getbootstrap.com/docs/5.3/components/popovers/
https://www.w3schools.com/bootstrap5/bootstrap_popover.php
https://www.tutorialspoint.com/bootstrap/bootstrap_popovers.htm

10. Spinners
https://getbootstrap.com/docs/5.3/components/spinners/
https://www.w3schools.com/bootstrap5/bootstrap_spinners.php
https://www.tutorialspoint.com/bootstrap/bootstrap_spinners.htm

11. YouTube | Bootstrap 5 Tutorial (Polish)
https://www.youtube.com/watch?v=Hgvx9hYlwe8

12. YouTube | Bootstrap 5 Tutorial (English)
https://www.youtube.com/watch?v=eow125xV5-c

13. YouTube | Bootstrap 5 Course (English)
https://www.youtube.com/watch?v=-qfEOE4vtxE

14. Pluralsight | Bootstrap 5: Fundamentals
https://www.pluralsight.com/courses/bootstrap-5-fundamentals

15. Pluralsight | Bootstrap 5 Components: Playbook
https://www.pluralsight.com/courses/bootstrap-components-playbook

**Comment by damianosiak** [comment]
Good job, thanks! :-)
