### ISSUE TITLE
Search for useful courses and tutorials for Google Maps API

### ISSUE THREAD

**Issue by damianosiak** [damianosiak/S2RouteAssistant#12]
Kamil, please search for useful courses and tutorials Google Maps API, basic will be enough
In addition, please provide appropriate references to Google documentation.

Thanks in advance for your help. :-)

**Comment by kamilgonsior** [comment]
Google Maps API - courses & tutorials

1. Maps
https://developers.google.com/maps/documentation/javascript/overview
https://developers.google.com/maps/documentation/javascript/reference/map
https://www.tutorialspoint.com/google_maps/google_maps_getting_started.htm
https://www.w3schools.com/graphics/google_maps_intro.asp
https://www.w3schools.com/graphics/google_maps_basic.asp
The Maps JavaScript API lets you customize maps with your own content and imagery for display on web pages and mobile devices. The Maps JavaScript API features four basic map types (roadmap, satellite, hybrid, and terrain) which you can modify using layers and styles, controls and events, and various services and libraries.
	

2. Directions Service
https://developers.google.com/maps/documentation/javascript/reference/directions
https://developers.google.com/maps/documentation/javascript/directions
A service for computing directions between two or more places

3. Geocoding Service
https://developers.google.com/maps/documentation/javascript/reference/geocoder
https://developers.google.com/maps/documentation/javascript/reference/coordinates
https://developers.google.com/maps/documentation/javascript/geocoding
A service for converting between an address and a LatLng.
A LatLng is a point in geographical coordinates: latitude and longitude.
Geocoding is the process of converting addresses (like "1600 Amphitheatre Parkway, Mountain View, CA") into geographic coordinates (like latitude 37.423021 and longitude -122.083739), which you can use to place markers or position the map.
Reverse geocoding is the process of converting geographic coordinates into a human-readable address.

4. Markers
https://developers.google.com/maps/documentation/javascript/reference/marker
https://developers.google.com/maps/documentation/javascript/markers
https://www.tutorialspoint.com/google_maps/google_maps_markers.htm
A marker identifies a location on a map. Markers and icons are objects of type Marker. 
Broadly speaking, markers are a type of overlay.
Markers are designed to be interactive. For example, by default they receive 'click' events, so you can add an event listener to bring up an info window displaying custom information. 

5. Event system
https://developers.google.com/maps/documentation/javascript/reference/event
https://developers.google.com/maps/documentation/javascript/events
https://www.tutorialspoint.com/google_maps/google_maps_events.htm
https://www.w3schools.com/graphics/google_maps_events.asp
JavaScript within the browser is event driven, meaning that JavaScript responds to interactions by generating events, and expects a program to listen to interesting events. 
Each Maps JavaScript API object exports a number of named events.

Is that enough?
As you asked, most of this is from the documentation
