### ISSUE TITLE
Introduction - Karol Nawrot

### ISSUE THREAD

**Issue by tomaszwylezek** [damianosiak/S2RouteAssistant#27]
The ticket is about to introduce Karol Nawrot into the project.
In the comment please describe what you can do and how you can help in this project and a bit about yourself
Also familiarize with what was done so far

**Comment by Physalium** [comment]
I am a full-stack developer with experience in .NET and React/Angular technologies. I also have some devops skills and cloud knowledge. I can help the project in CI/CD and cloud hosting areas.
