### ISSUE TITLE
Introduction - Szymon Buniewicz

### ISSUE THREAD

**Issue by tomaszwylezek** [damianosiak/S2RouteAssistant#29]
The ticket is about to introduce Szymon Buniewicz into the project.
In the comment please describe what you can do and how you can help in this project and a bit about yourself
Also familiarize with what was done so far

**Comment by szymonbuniewicz** [comment]
I am Cybersecurity specialist, working in the blue team. I deal with administration of security systems, also monitor and report status of cybersecurity in incovered organizations. In my free time I'm learning programming especially Golang.
