### ISSUE TITLE
Initial code setup

### ISSUE THREAD

**Issue by tomaszwylezek** [damianosiak/S2RouteAssistant#30]
Base app setup

**Comment by damianosiak** [comment]
Base app created - https://github.com/damianosiak/S2RouteAssistant

1. HTML - https://github.com/damianosiak/S2RouteAssistant/blob/main/index.html
2. CSS - https://github.com/damianosiak/S2RouteAssistant/blob/main/styles.css
3. JS - https://github.com/damianosiak/S2RouteAssistant/blob/main/logic.js

Below details:

1. The application structure created - split into html, css and js
2. The Google Cloud account created  - for using Google Maps API
3. The Google Maps API key generated
4. Custom css styles created
5. Basic app functions (logic) created
- displaying Google map
- getting current location and map centering
- address search based on the information entered
- displaying the list of added points - (selected on map)
- calculating the most optimal route - (driving)
- displaying details of the most optimal route
- displaying summary about the calculated route
- ability to reset the map
