### ISSUE TITLE
Adjustment of route assistant

### ISSUE THREAD

**Issue by tomaszwylezek** [damianosiak/S2RouteAssistant#34]
Details to be added by @damianosiak

**Comment by damianosiak** [comment]
Update HTML structure, CSS styles and logic (js)
The app will allow to determine the best route using four options - DRIVING, BIKING, TRANSIT, WALKING
A loading panel with percent and estimated time will be added
The calculated route will be able to run in the Google Maps app

**Comment by damianosiak** [comment]
Update has been done and uploaded to main branch
https://github.com/damianosiak/S2RouteAssistant

**Comment by damianosiak** [comment]
Waiting for tests from #36 and #37

**Comment by damianosiak** [comment]
The problems that were reported in #36 and #37 have been resolved.
Everything works properly now :-)
