### ISSUE TITLE
Add working download button

### ISSUE THREAD

**Issue by tomaszwylezek** [damianosiak/S2RouteAssistant#74]
## Description

The ticket is about to add functionality to the details section to download information about the route, as the current button is only a placeholder.

## Acceptance criteria

- There is a possibility to click on a button to trigger downloading a PDF with information about the best route
- The PDF report is downloaded after click
- The PDF contains information about best route

**Comment by damianosiak** [comment]
The update has been prepared.
- Added download button to save the result in PDF format
- Improved route calculation algorithm
- Added opening of the calculated route in the dedicated Google Maps application
- Fixed minor graphical errors

A pull request has been created #84
