### ISSUE TITLE
Pipeline for auto deploy

### ISSUE THREAD

**Issue by tomaszwylezek** [damianosiak/S2RouteAssistant#76]
## Description

The ticket is about creating a pipeline for the deployment of the application.

## Acceptance criteria

- The pipeline exists and deploys applications properly when the change is applied

**Comment by Physalium** [comment]
The pipeline "DEPLOY TO AWS S3" has been created.

The action is triggered by closed pull requests and by manual workflow dispatch.
I had to move our website files to a folder named static so that we don't transfer .git files to S3 bucket
