### ISSUE TITLE
Cypress investigation

### ISSUE THREAD

**Issue by tomaszwylezek** [damianosiak/S2RouteAssistant#78]
## Description

The ticket is about to investigate Cypress as a framework for E2E tests.

## Acceptance criteria

- The investigation is done and based on that we can make a decision if we want to use it or the second framework

**Comment by kamilgonsior** [comment]
Cypress is an open-source end-to-end testing framework that is designed to make it easy to write and run automated tests for web applications. End-to-end (E2E) testing involves testing the entire application flow, simulating real user interactions to ensure that the application behaves as expected. Cypress is specifically focused on making E2E testing simple, fast, and reliable.

Here are some key characteristics and features of Cypress:

- Primarily built using JavaScript, leverages popular JavaScript libraries and tools, such as Mocha for test structuring and Chai for assertions.

- Tests are written in a clear and declarative syntax, which makes them easy to read and understand. The framework provides a high-level API for interacting with the application under test.

- Allows developers to debug their tests by taking snapshots at different points during test execution.

Overall, Cypress is a powerful and developer-friendly E2E testing framework that aims to simplify the process of writing and maintaining tests for web applications. Its features and ease of use have contributed to its popularity among developers for ensuring the quality and reliability of web applications.
