### ISSUE TITLE
Investigation about accessibility and speed index

### ISSUE THREAD

**Issue by tomaszwylezek** [damianosiak/S2RouteAssistant#81]
## Description

The ticket is about investigating if the accessibility and speed index of the page is important for our user and how much effort we should put into it

## Acceptance criteria

- We have knowledge about how important is accessibility and speed index in our page for our clients.

**Comment by szymonbuniewicz** [comment]
I created a survey about accessibility and speed index: https://forms.gle/wvSB5x3fKKrDpna98

Below are charts illustrating user responses:
![Screenshot from 2023-11-25 16-10-03](https://github.com/damianosiak/S2RouteAssistant/assets/148790357/fe93306e-2a23-4372-9dc0-438b061385d5)
![Screenshot from 2023-11-25 16-10-32](https://github.com/damianosiak/S2RouteAssistant/assets/148790357/03054594-1600-45f2-af87-1e147133de51)
![Screenshot from 2023-11-25 16-11-41](https://github.com/damianosiak/S2RouteAssistant/assets/148790357/061b4fe8-2b3a-4fa7-81ef-83600553a501)
![Screenshot from 2023-11-25 16-25-42](https://github.com/damianosiak/S2RouteAssistant/assets/148790357/674cf974-3b66-4279-9ec5-6094e4d2c23f)
![Screenshot from 2023-11-25 16-25-59](https://github.com/damianosiak/S2RouteAssistant/assets/148790357/efc7d174-6a84-4890-98a7-b40b17755162)

![Screenshot from 2023-11-25 16-26-36](https://github.com/damianosiak/S2RouteAssistant/assets/148790357/ba4de811-7c96-4eac-b2d4-415becaf4085)
![Screenshot from 2023-11-25 16-26-59](https://github.com/damianosiak/S2RouteAssistant/assets/148790357/76196161-4913-4c31-af3a-b2b1f0b33232)

![Screenshot from 2023-11-25 16-27-10](https://github.com/damianosiak/S2RouteAssistant/assets/148790357/a3171149-df86-4181-acb0-985e7c463c18)
![Screenshot from 2023-11-25 16-27-30](https://github.com/damianosiak/S2RouteAssistant/assets/148790357/9c6afdd6-7878-445f-9e42-987d28de2f97)

**Conclusions:**
Considering the responses from users, it is evident that conducting accessibility and speed index checks is essential. Several users have highlighted challenges related to accessibility, such as color contrast, unclear button labels or font size too big. Additionally, concerns about slow loading experiences on page, including slow loading during route creation, have been raised. To address these issues and enhance the overall user experience, it is recommended to prioritize accessibility and speed index checks to identify and rectify potential issues. But overall, users are happy with our product.
